import React from 'react';

const HTML = "\n  <div class=\"amb\"><div class=\"bigicon drift\" data-speed=\"0.05\" style=\"width:400px;height:400px;left:-60px;top:40px;\"><svg viewBox=\"0 0 24 24\"><use href=\"#ic-spark\"></use></svg></div><div class=\"halfcircle drift\" data-speed=\"0.12\" style=\"width:360px;height:360px;right:-160px;bottom:-140px;\"></div></div>\n  <div class=\"wrap\">\n  <div class=\"eyebrow-row reveal\"><span class=\"num\">06</span><span class=\"kicker\">Questions</span><span class=\"ln\"></span></div>\n  <h2 class=\"h-sec reveal\">Everything you need to <span class=\"accent-i\">know.</span></h2>\n  <div class=\"faq-list\">\n    <div class=\"faq-item reveal\"><button class=\"faq-q\">What does it cost — I mean ALL the charges?<span class=\"pm\">+</span></button><div class=\"faq-a\"><div class=\"faq-a-inner\">A tiered success fee of 3–5%, agreed before you sign, and nothing else. No retainer, no monthly fee, no hidden line items. If we don't close, you don't pay.</div></div></div>\n    <div class=\"faq-item reveal\"><button class=\"faq-q\">Will my competitors or team find out I'm exploring a sale?<span class=\"pm\">+</span></button><div class=\"faq-a\"><div class=\"faq-a-inner\">Not unless you decide they should. Buyers see an anonymous, range-only profile. No introduction happens, and your identity is never revealed, without your explicit approval on each name.</div></div></div>\n    <div class=\"faq-item reveal\"><button class=\"faq-q\">How is this different from a traditional investment bank?<span class=\"pm\">+</span></button><div class=\"faq-a\"><div class=\"faq-a-inner\">Same calibre of banker and outcome — without the retainer, the year-long timeline, or the minimum deal size. AI does the heavy lifting on valuation, materials and buyer mapping, so your banker spends their time where judgement matters.</div></div></div>\n    <div class=\"faq-item reveal\"><button class=\"faq-q\">Is the AI just drafting things with ChatGPT?<span class=\"pm\">+</span></button><div class=\"faq-a\"><div class=\"faq-a-inner\">No. Our models are trained on real transaction data and run against a verified buyer network. Everything AI produces — the IM, the teaser, the buyer list — is reviewed and rewritten by a senior banker before it leaves the building.</div></div></div>\n    <div class=\"faq-item reveal\"><button class=\"faq-q\">What size of deal do you work on?<span class=\"pm\">+</span></button><div class=\"faq-a\"><div class=\"faq-a-inner\">We specialise in ₹12–200 Cr transactions — raises and exits — the band most legacy banks ignore and most marketplaces can't serve well.</div></div></div>\n  </div>\n  </div>\n";

export default function Faq() {
  return (
    <section className="section-pad framed" id="faq" data-screen-label="FAQ" dangerouslySetInnerHTML={{ __html: HTML }} />
  );
}
