import React from 'react';

const HTML = "\n  <div class=\"amb\"><div class=\"halfcircle drift\" data-speed=\"0.16\" style=\"width:260px;height:260px;left:-100px;top:10%;\"></div><div class=\"halfcircle warm drift\" data-speed=\"0.09\" style=\"width:220px;height:220px;right:-80px;bottom:-60px;\"></div></div>\n  <div class=\"wrap\">\n    <div class=\"eyebrow-row reveal\" style=\"justify-content:center;\"><span class=\"num\">07</span><span class=\"kicker\">Backed by</span></div>\n    <h2 class=\"h-sec reveal\" style=\"text-align:center;margin-inline:auto;\">Trusted by the best <span class=\"accent-copper\">investors.</span></h2>\n    <div class=\"inv4 reveal\" aria-label=\"Our investors\">\n      <div class=\"inv4-track\">\n        <img src=\"/assets/bd0dbe67fa07.svg\" alt=\"Gruhas\" draggable=\"false\">\n        <img src=\"/assets/89ed8fe4345e.svg\" alt=\"Raisers Edge\" draggable=\"false\">\n        <img src=\"/assets/dee43c50557c.svg\" alt=\"Capital A\" draggable=\"false\">\n        <img src=\"/assets/a7b1288648d7.svg\" alt=\"We Founder Circle\" draggable=\"false\">\n        <img src=\"/assets/e240ef249bd2.svg\" alt=\"Dezerv Innovation Fund\" draggable=\"false\">\n        <img src=\"/assets/bd0dbe67fa07.svg\" alt=\"\" aria-hidden=\"true\" draggable=\"false\">\n        <img src=\"/assets/89ed8fe4345e.svg\" alt=\"\" aria-hidden=\"true\" draggable=\"false\">\n        <img src=\"/assets/dee43c50557c.svg\" alt=\"\" aria-hidden=\"true\" draggable=\"false\">\n        <img src=\"/assets/a7b1288648d7.svg\" alt=\"\" aria-hidden=\"true\" draggable=\"false\">\n        <img src=\"/assets/e240ef249bd2.svg\" alt=\"\" aria-hidden=\"true\" draggable=\"false\">\n      </div>\n    </div>\n  </div>\n";

export default function Investors() {
  return (
    <section className="section-pad investors3 framed" data-screen-label="Investors" dangerouslySetInnerHTML={{ __html: HTML }} />
  );
}
