import React from 'react';

const HTML = "\n  <div class=\"amb\"><div class=\"halfcircle\" data-speed=\"0.001\" style=\"width:320px;height:320px;right:-120px;top:48px;\"></div><div class=\"halfcircle warm\" data-speed=\"0.001\" style=\"width:240px;height:240px;left:-90px;bottom:48px;\"></div></div>\n  <div class=\"wrap\">\n    <h2 class=\"h-sec reveal\">The numbers a bank is <span class=\"accent-i\">judged on.</span></h2>\n    <div class=\"track-grid2\">\n      <div class=\"tcard reveal\">\n        <div class=\"tg\">\n          <span class=\"tg-glow\" style=\"left:4px;bottom:0;width:46px;height:104px;border-radius:15px;\"></span>\n          <span class=\"tg-dim\" style=\"left:62px;bottom:0;width:46px;height:38px;border-radius:13px;\"></span>\n        </div>\n        <div class=\"tn\" data-count=\"30\">30</div><div class=\"tl\">Mandates closed across raise &amp; exit</div>\n      </div>\n      <div class=\"tcard reveal\">\n        <div class=\"tg\">\n          <span class=\"tg-ring\" style=\"left:56px;width:128px;height:128px;bottom:64px;\"></span>\n          <span class=\"tg-ring\" style=\"left:56px;width:90px;height:90px;opacity:.65;bottom:64px;\"></span>\n          <span class=\"tg-coin\" style=\"left:56px;bottom:64px;\"></span>\n        </div>\n        <div class=\"tn\" data-count=\"3000\" data-prefix=\"₹\" data-comma=\"1\">₹3,000<span class=\"u\">&nbsp;Cr</span></div><div class=\"tl\">Cumulative deal value transacted</div>\n      </div>\n      <div class=\"tcard reveal\">\n        <div class=\"tg\">\n          <span class=\"tg-pill on\" style=\"left:4px;bottom:46px;width:96px;\"></span>\n          <span class=\"tg-pill\" style=\"left:4px;bottom:0;width:158px;\"></span>\n        </div>\n        <div class=\"tn\" data-count=\"14\">14<span class=\"u\">&nbsp;wks</span></div><div class=\"tl\">Median time to close vs. 9-month industry norm</div>\n      </div>\n      <div class=\"tcard reveal\">\n        <div class=\"tg\">\n          <span class=\"tg-step\" style=\"left:4px;height:38px;\"></span>\n          <span class=\"tg-step mid\" style=\"left: 62px; height: 66px; background-color: rgb(93, 113, 255)\" data-comment-anchor=\"2bb6c899aa-span\"></span>\n          <span class=\"tg-step glow\" style=\"left:120px;height:100px;\"></span>\n        </div>\n        <div class=\"tn\" data-count=\"1.9\" data-decimals=\"1\">1.9<span class=\"u\">×</span></div><div class=\"tl\">Median valuation uplift on first offer</div>\n      </div>\n    </div>\n  </div>\n";

export default function TrackRecord() {
  return (
    <section className="track framed" data-screen-label="Track record" dangerouslySetInnerHTML={{ __html: HTML }} />
  );
}
